#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Convert-Binary-C
Version  : 0.78
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.78.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.78.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libconvert-binary-c-perl/libconvert-binary-c-perl_0.78-1.debian.tar.xz
Summary  : 'Binary Data Conversion using C Types'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Convert-Binary-C-bin
Requires: perl-Convert-Binary-C-lib
Requires: perl-Convert-Binary-C-man

%description
CONTENTS
1. DESCRIPTION
2. INSTALLATION
3. UPGRADING
4. DOCUMENTATION
5. MAILING LIST
6. CONFIGURATION
7. COMPATIBILITY
8. FEATURES
9. COPYRIGHT

%package bin
Summary: bin components for the perl-Convert-Binary-C package.
Group: Binaries
Requires: perl-Convert-Binary-C-man

%description bin
bin components for the perl-Convert-Binary-C package.


%package lib
Summary: lib components for the perl-Convert-Binary-C package.
Group: Libraries

%description lib
lib components for the perl-Convert-Binary-C package.


%package man
Summary: man components for the perl-Convert-Binary-C package.
Group: Default

%description man
man components for the perl-Convert-Binary-C package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Convert-Binary-C-0.78
mkdir -p %{_topdir}/BUILD/Convert-Binary-C-0.78/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Convert-Binary-C-0.78/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Convert/Binary/C.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Convert/Binary/C/Cached.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/ccconfig

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Convert/Binary/C/C.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/ccconfig.1
/usr/share/man/man3/Convert::Binary::C.3
/usr/share/man/man3/Convert::Binary::C::Cached.3
