#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Convert-Binary-C
Version  : 0.78
Release  : 7
URL      : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.78.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.78.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libconvert-binary-c-perl/libconvert-binary-c-perl_0.78-1.debian.tar.xz
Summary  : 'Binary Data Conversion using C Types'
Group    : Development/Tools
License  : Artistic-1.0-Perl BSD-3-Clause GPL-2.0 LGPL-2.1 MIT Rdisc
Requires: perl-Convert-Binary-C-bin = %{version}-%{release}
Requires: perl-Convert-Binary-C-lib = %{version}-%{release}
Requires: perl-Convert-Binary-C-license = %{version}-%{release}
Requires: perl-Convert-Binary-C-man = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
CONTENTS
1. DESCRIPTION
2. INSTALLATION
3. UPGRADING
4. DOCUMENTATION
5. MAILING LIST
6. CONFIGURATION
7. COMPATIBILITY
8. FEATURES
9. COPYRIGHT

%package bin
Summary: bin components for the perl-Convert-Binary-C package.
Group: Binaries
Requires: perl-Convert-Binary-C-license = %{version}-%{release}
Requires: perl-Convert-Binary-C-man = %{version}-%{release}

%description bin
bin components for the perl-Convert-Binary-C package.


%package dev
Summary: dev components for the perl-Convert-Binary-C package.
Group: Development
Requires: perl-Convert-Binary-C-lib = %{version}-%{release}
Requires: perl-Convert-Binary-C-bin = %{version}-%{release}
Provides: perl-Convert-Binary-C-devel = %{version}-%{release}

%description dev
dev components for the perl-Convert-Binary-C package.


%package lib
Summary: lib components for the perl-Convert-Binary-C package.
Group: Libraries
Requires: perl-Convert-Binary-C-license = %{version}-%{release}

%description lib
lib components for the perl-Convert-Binary-C package.


%package license
Summary: license components for the perl-Convert-Binary-C package.
Group: Default

%description license
license components for the perl-Convert-Binary-C package.


%package man
Summary: man components for the perl-Convert-Binary-C package.
Group: Default

%description man
man components for the perl-Convert-Binary-C package.


%prep
%setup -q -n Convert-Binary-C-0.78
cd ..
%setup -q -T -D -n Convert-Binary-C-0.78 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Convert-Binary-C-0.78/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Convert-Binary-C
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Convert-Binary-C/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/Convert/Binary/C.pm
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/Convert/Binary/C/Cached.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/ccconfig

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Convert::Binary::C.3
/usr/share/man/man3/Convert::Binary::C::Cached.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/auto/Convert/Binary/C/C.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Convert-Binary-C/deblicense_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ccconfig.1
