#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Convert-Binary-C
Version  : 0.84
Release  : 27
URL      : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.84.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MH/MHX/Convert-Binary-C-0.84.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libconvert-binary-c-perl/libconvert-binary-c-perl_0.78-1.debian.tar.xz
Summary  : 'Binary Data Conversion using C Types'
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.1 MIT Rdisc
Requires: perl-Convert-Binary-C-bin = %{version}-%{release}
Requires: perl-Convert-Binary-C-license = %{version}-%{release}
Requires: perl-Convert-Binary-C-man = %{version}-%{release}
Requires: perl-Convert-Binary-C-perl = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan

%description
The 'examples' directory is empty until you actually
build the module. The example scripts will then be
automatically generated.

%package bin
Summary: bin components for the perl-Convert-Binary-C package.
Group: Binaries
Requires: perl-Convert-Binary-C-license = %{version}-%{release}

%description bin
bin components for the perl-Convert-Binary-C package.


%package dev
Summary: dev components for the perl-Convert-Binary-C package.
Group: Development
Requires: perl-Convert-Binary-C-bin = %{version}-%{release}
Provides: perl-Convert-Binary-C-devel = %{version}-%{release}
Requires: perl-Convert-Binary-C = %{version}-%{release}

%description dev
dev components for the perl-Convert-Binary-C package.


%package license
Summary: license components for the perl-Convert-Binary-C package.
Group: Default

%description license
license components for the perl-Convert-Binary-C package.


%package man
Summary: man components for the perl-Convert-Binary-C package.
Group: Default

%description man
man components for the perl-Convert-Binary-C package.


%package perl
Summary: perl components for the perl-Convert-Binary-C package.
Group: Default
Requires: perl-Convert-Binary-C = %{version}-%{release}

%description perl
perl components for the perl-Convert-Binary-C package.


%prep
%setup -q -n Convert-Binary-C-0.84
cd %{_builddir}
tar xf %{_sourcedir}/libconvert-binary-c-perl_0.78-1.debian.tar.xz
cd %{_builddir}/Convert-Binary-C-0.84
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Convert-Binary-C-0.84/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Convert-Binary-C
cp %{_builddir}/Convert-Binary-C-0.84/tests/include/pdclib/COPYING.CC0 %{buildroot}/usr/share/package-licenses/perl-Convert-Binary-C/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Convert-Binary-C/7c140b1599f7b490e0427b1dd4da10470d3da1b5
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ccconfig

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Convert::Binary::C.3
/usr/share/man/man3/Convert::Binary::C::Cached.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Convert-Binary-C/7c140b1599f7b490e0427b1dd4da10470d3da1b5
/usr/share/package-licenses/perl-Convert-Binary-C/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ccconfig.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
